import DeRhamCohomology.AlternatingMap.Curry
import DeRhamCohomology.ContinuousAlternatingMap.Curry
import DeRhamCohomology.Fin
import DeRhamCohomology.MultilinearMap.Fin
import DeRhamCohomology.Perm
